name = "AlgebraicABMS"
uuid = "1301f41b-2c8a-4430-9d85-ab97d23a62cd"
license = "MIT"
authors = ["AlgebraicJulia Developer <email@algebraicjulia.org>"]
version = "0.0.1"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"

[compat]
Catlab = "^0.16"
julia = "1.6"
